// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnumerateMonitors() {
  return window['go']['main']['App']['EnumerateMonitors']();
}

export function HasInputPermission() {
  return window['go']['main']['App']['HasInputPermission']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RequestInputPermission() {
  return window['go']['main']['App']['RequestInputPermission']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
