// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CertFingerprint() {
  return window['go']['main']['App']['CertFingerprint']();
}

export function ClearClipboardHistory() {
  return window['go']['main']['App']['ClearClipboardHistory']();
}

export function GetClipboardHistory() {
  return window['go']['main']['App']['GetClipboardHistory']();
}

export function GetPlacements() {
  return window['go']['main']['App']['GetPlacements']();
}

export function GetServerMonitors() {
  return window['go']['main']['App']['GetServerMonitors']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RestoreClipboardItem(arg1) {
  return window['go']['main']['App']['RestoreClipboardItem'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetClientPlacement(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetClientPlacement'](arg1, arg2, arg3);
}

export function ShowClipboardHistory() {
  return window['go']['main']['App']['ShowClipboardHistory']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
