// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CertFingerprint():Promise<string>;

export function IsRunning():Promise<boolean>;

export function LoadConfig():Promise<main.ConfigDTO>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;

export function Start(arg1:main.ConfigDTO):Promise<void>;

export function Stop():Promise<void>;
